fn_single_line = true
# format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
match_arm_blocks = false
normalize_comments = true
reorder_impl_items = true
struct_lit_single_line = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
